
close all
load('debiased_data_EX12')

m = 100; tau = 1/m;  t = tau/2:tau:1-tau/2;
x_real = (-6*t.^2.*(1-t).*(2-8*t+7*t.^2))';
figure(4);
plot( t',x_real,'-',...%    t',x_CG,'>',...
    t',de_x_land_3,'-',...
    t',de_x_09_3,'-.',...
    t',de_x_15_3,'--', ...%    t',x_19,'-', ...
    t',de_x_199_3,'-', ...
    LineWidth=2)
% 创建 title
% title({'solution, noise level 5%'},fontsize=20);
title({'debiased solutions for Example 1(1)'},fontsize=20);
legend('exact',...%'CG',
    'debiased Landweber','debiased FAR,\theta = 0.9',...
    'debiased FAR,\theta = 1.5', ...%    'FAR,\theta = 1.9', ...
    'debiased FAR,\theta = 1.99', ...
    fontsize=20)